# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
            docker-compose build
            docker-compose up -d
    - run: |
            docker-compose run --rm web npx knex migrate:latest
            docker-compose run --rm web npx knex seed:run
    
    - run: docker-compose run --rm web npm test

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin ${{ github.base_ref }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with: 
          node-version: '12'
      - run: npm install
      - run: node ci_linter_helper.js
